name: Lighthouse

on:
  pull_request:
    branches:
      - "**"

jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Start preview server
        run: npm run preview &
      - name: Wait for server
        run: npx wait-on http://localhost:4173
      - name: Run Lighthouse CI
        run: npx lhci autorun --collect.url=http://localhost:4173
