name: Prettier

on:
  pull_request:
    branches:
      - "**"

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run Prettier check
        run: npm run prettier
