name: TS Unused Exports

on:
  pull_request:
    branches:
      - "**"

jobs:
  ts-unused-exports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Check for unused exports (ts-unused-exports)
        run: npx ts-unused-exports ./tsconfig.json
